controllers:
    resource: ../src/Controller/
    type: annotation

index:
    path: /{page}
    requirements:
        page: "^(?!api).*"
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'index.html.twig'

kernel:
    resource: ../src/Kernel.php
    type: annotation
